In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [2]:
df=pd.read_excel('WaitData.Published.xlsx', 'F1')

In [4]:
df.head()

,Wait,x_ArrivalDTTM,x_ScheduledDTTM,x_BeginDTTM,SumHowEarlyWaiting,AvgHowEarlyWaiting,LineCount0Strict,SumWaits,LineCount0,LineCount1,...,NumAddOnsToday,NumAddOnsLastW2,NumScheduledNextSlot,NumScheduledNextW2,SumTimeToCompleteNextSlot,SumTimeToCompleteNextW2,WithContrastCountWaiting,WithAndWithoutContrastCountWaiting,WithContrastCountInProgress,WithAndWithoutContrastCountInProgress
0,-8,2025-08-02 17:47:12,2025-08-02 18:00:00,2025-08-02 17:52:13,0,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,0
1,-2,2025-08-02 17:25:43,2025-08-02 17:30:00,2025-08-02 17:28:39,0,0,0,0,0,0,...,3,0,1,1,27,27,0,0,0,0
2,10,2025-08-02 17:00:41,2025-08-02 17:00:00,2025-08-02 17:10:18,-13,-13,1,17,1,2,...,3,0,1,2,37,64,0,0,0,0
3,35,2025-08-02 16:43:19,2025-08-02 16:30:00,2025-08-02 17:05:31,-1,-1,1,12,1,1,...,3,0,1,2,37,74,0,0,0,0
4,19,2025-08-02 16:31:15,2025-08-02 16:30:00,2025-08-02 16:49:38,15,15,1,16,1,2,...,3,0,1,2,37,74,0,0,0,0

In [5]:
drop_column=['x_ArrivalDTTM','x_BeginDTTM','SumHowEarlyWaiting','AvgHowEarlyWaiting','LineCount0Strict','SumWaits','LineCount0',
            'LineCount1','LineCount2','LineCount3','LineCount4','FlowCount2','FlowCount4','SchFlowCount2','SchFlowCount4',
            'FutFlowCount2','FutFlowCount4','mintime','maxtime','NumScannersUsedToday','SumInProgress','Median5','MostRecent1',
            'MostRecent2','MostRecent3','MostRecent4','MostRecent5','StartTime','StartTime2','StartTime3','StartTime4',
            'NoneInProgress','NoneCompleted','NoneInLine','SumWaitByTaskTypeLine','AvgWaitByTaskTypeLine',
            'SumTimeToCompleteInProgress','DelayedInLine','SumDelayWaitingByExamCode','SumDelayWaitingInLine',
            'SumDelayInProgress','ExpectedDelayNextExam','AvgAgePeopleWaiting','AvgWaitLastK1Customers','AvgWaitLastK2Customers',
            'AvgWaitLastK3Customers','AvgWaitLastW1','AvgWaitLastW2','AvgWaitLastW3','AvgDelayForDay','NumScheduledNextW2',
            'SumTimeToCompleteNextSlot','SumTimeToCompleteNextW2','WithContrastCountWaiting','WithAndWithoutContrastCountWaiting',
            'WithContrastCountInProgress','WithAndWithoutContrastCountInProgress']

In [6]:
df = df.drop(drop_column, axis=1)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42766 entries, 0 to 42765
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Wait                    42766 non-null  int64
 1   x_ScheduledDTTM         42766 non-null  datetime64[ns]
 2   DelayCount              42766 non-null  int64
 3   DelayCountLastHour      42766 non-null  int64
 4   AheadCount              42766 non-null  int64
 5   ThoracicCount           42766 non-null  int64
 6   PediatricCount          42766 non-null  int64
 7   NeuroCount              42766 non-null  int64
 8   AbdominalCount          42766 non-null  int64
 9   VascularCount           42766 non-null  int64
 10  CardiacCount            42766 non-null  int64
 11  MSKCount                42766 non-null  int64
 12  BeforeSlot              42766 non-null  int64
 13  AfterSlot               42766 non-null  int64
 14  IsLast                  42766 non-null  int64
 15  IsFirst                 42766 non-null  int64
 16  DayOfWeek               42765 non-null  float64
 17  Month                   42765 non-null  float64
 18  DayOfYear               42765 non-null  float64
 19  InProgressSize          42766 non-null  int64
 20  NumCompletedToday       42766 non-null  int64
 21  NumCompletedInLastW1    42766 non-null  int64
 22  NumCompletedInLastW2    42766 non-null  int64
 23  NumCompletedInLastW3    42766 non-null  int64
 24  NumCustomersInLastW1    42766 non-null  int64
 25  NumCustomersInLastW2    42766 non-null  int64
 26  NumCustomersInLastW3    42766 non-null  int64
 27  OutpatientWaitingCount  42766 non-null  int64
 28  MalesWaitingCount       42766 non-null  int64
 29  NumAddOnsToday          42766 non-null  int64
 30  NumAddOnsLastW2         42766 non-null  int64
 31  NumScheduledNextSlot    42766 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(28)
memory usage: 10.4 MB

In [8]:
df[df['DayOfWeek'].isnull()]['DayOfWeek']

41311   NaN
Name: DayOfWeek, dtype: float64

In [9]:
df = df.drop(41311, axis=0)

In [10]:
df.isnull().sum()

Wait                      0
x_ScheduledDTTM           0
DelayCount                0
DelayCountLastHour        0
AheadCount                0
ThoracicCount             0
PediatricCount            0
NeuroCount                0
AbdominalCount            0
VascularCount             0
CardiacCount              0
MSKCount                  0
BeforeSlot                0
AfterSlot                 0
IsLast                    0
IsFirst                   0
DayOfWeek                 0
Month                     0
DayOfYear                 0
InProgressSize            0
NumCompletedToday         0
NumCompletedInLastW1      0
NumCompletedInLastW2      0
NumCompletedInLastW3      0
NumCustomersInLastW1      0
NumCustomersInLastW2      0
NumCustomersInLastW3      0
OutpatientWaitingCount    0
MalesWaitingCount         0
NumAddOnsToday            0
NumAddOnsLastW2           0
NumScheduledNextSlot      0
dtype: int64

In [13]:
df['x_ScheduledHour'] = df['x_ScheduledDTTM'].map(lambda date: date.hour)
df['x_ScheduledMinute'] = df['x_ScheduledDTTM'].map(lambda date: date.minute)

In [14]:
df.head()

,Wait,x_ScheduledDTTM,DelayCount,DelayCountLastHour,AheadCount,ThoracicCount,PediatricCount,NeuroCount,AbdominalCount,VascularCount,...,NumCustomersInLastW1,NumCustomersInLastW2,NumCustomersInLastW3,OutpatientWaitingCount,MalesWaitingCount,NumAddOnsToday,NumAddOnsLastW2,NumScheduledNextSlot,x_ScheduledHour,x_ScheduledMinute
0,-8,2025-08-02 18:00:00,30,3,63,0,0,0,1,0,...,2,3,12,1,0,3,0,0,18,0
1,-2,2025-08-02 17:30:00,30,6,62,0,0,0,2,0,...,2,4,15,1,0,3,0,1,17,30
2,10,2025-08-02 17:00:00,28,6,61,0,0,0,3,2,...,3,8,16,2,0,3,0,1,17,0
3,35,2025-08-02 16:30:00,27,6,58,0,0,0,3,3,...,7,12,17,2,1,3,0,1,16,30
4,19,2025-08-02 16:30:00,26,6,58,0,0,0,4,2,...,6,11,17,2,1,3,0,1,16,30

In [15]:
df = df.drop('x_ScheduledDTTM', axis=1)

In [16]:
df.head()

,Wait,DelayCount,DelayCountLastHour,AheadCount,ThoracicCount,PediatricCount,NeuroCount,AbdominalCount,VascularCount,CardiacCount,...,NumCustomersInLastW1,NumCustomersInLastW2,NumCustomersInLastW3,OutpatientWaitingCount,MalesWaitingCount,NumAddOnsToday,NumAddOnsLastW2,NumScheduledNextSlot,x_ScheduledHour,x_ScheduledMinute
0,-8,30,3,63,0,0,0,1,0,0,...,2,3,12,1,0,3,0,0,18,0
1,-2,30,6,62,0,0,0,2,0,0,...,2,4,15,1,0,3,0,1,17,30
2,10,28,6,61,0,0,0,3,2,0,...,3,8,16,2,0,3,0,1,17,0
3,35,27,6,58,0,0,0,3,3,0,...,7,12,17,2,1,3,0,1,16,30
4,19,26,6,58,0,0,0,4,2,0,...,6,11,17,2,1,3,0,1,16,30

In [17]:
df.to_csv('WaitDataF1', index=False)

In [18]:
df = pd.read_csv('WaitDataF1')

In [20]:
df = pd.read_excel('WaitData.Published.xlsx', 'F2')

In [21]:
df.head()

,Wait,x_ArrivalDTTM,x_ScheduledDTTM,x_BeginDTTM,SumHowEarlyWaiting,AvgHowEarlyWaiting,LineCount0Strict,SumWaits,LineCount0,LineCount1,...,NumAddOnsToday,NumAddOnsLastW2,NumScheduledNextSlot,NumScheduledNextW2,SumTimeToCompleteNextSlot,SumTimeToCompleteNextW2,WithContrastCountWaiting,WithAndWithoutContrastCountWaiting,WithContrastCountInProgress,WithAndWithoutContrastCountInProgress
0,23,2025-08-02 18:14:13,2025-08-02 18:45:00,2025-08-02 19:08:59,253,63,4,264,4,4,...,1,0,0,0,0,0,0,5,0,3
1,13,2025-08-02 17:48:10,2025-08-02 18:45:00,2025-08-02 18:58:13,185,46,4,212,4,5,...,1,0,0,1,0,42,0,5,0,2
2,16,2025-08-02 17:32:23,2025-08-02 18:15:00,2025-08-02 18:31:32,167,41,4,190,4,5,...,1,0,2,0,90,0,0,5,0,1
3,35,2025-08-02 17:08:12,2025-08-02 17:45:00,2025-08-02 18:20:27,178,44,3,120,4,3,...,1,0,1,0,50,0,0,5,0,1
4,65,2025-08-02 16:56:18,2025-08-02 16:45:00,2025-08-02 17:50:21,189,63,0,72,3,3,...,1,0,1,1,48,60,0,4,0,2

In [22]:
df = df.drop(drop_column, axis=1)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15652 entries, 0 to 15651
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Wait                    15652 non-null  int64
 1   x_ScheduledDTTM         15652 non-null  datetime64[ns]
 2   DelayCount              15652 non-null  int64
 3   DelayCountLastHour      15652 non-null  int64
 4   AheadCount              15652 non-null  int64
 5   ThoracicCount           15652 non-null  int64
 6   PediatricCount          15652 non-null  int64
 7   NeuroCount              15652 non-null  int64
 8   AbdominalCount          15652 non-null  int64
 9   VascularCount           15652 non-null  int64
 10  CardiacCount            15652 non-null  int64
 11  MSKCount                15652 non-null  int64
 12  BeforeSlot              15652 non-null  int64
 13  AfterSlot               15652 non-null  int64
 14  IsLast                  15652 non-null  int64
 15  IsFirst                 15652 non-null  int64
 16  DayOfWeek               15652 non-null  int64
 17  Month                   15652 non-null  int64
 18  DayOfYear               15652 non-null  int64
 19  InProgressSize          15652 non-null  int64
 20  NumCompletedToday       15652 non-null  int64
 21  NumCompletedInLastW1    15652 non-null  int64
 22  NumCompletedInLastW2    15652 non-null  int64
 23  NumCompletedInLastW3    15652 non-null  int64
 24  NumCustomersInLastW1    15652 non-null  int64
 25  NumCustomersInLastW2    15652 non-null  int64
 26  NumCustomersInLastW3    15652 non-null  int64
 27  OutpatientWaitingCount  15652 non-null  int64
 28  MalesWaitingCount       15652 non-null  int64
 29  NumAddOnsToday          15652 non-null  int64
 30  NumAddOnsLastW2         15652 non-null  int64
 31  NumScheduledNextSlot    15652 non-null  int64
dtypes: datetime64[ns](1), int64(31)
memory usage: 3.8 MB

In [24]:
df.isnull().sum()

Wait                      0
x_ScheduledDTTM           0
DelayCount                0
DelayCountLastHour        0
AheadCount                0
ThoracicCount             0
PediatricCount            0
NeuroCount                0
AbdominalCount            0
VascularCount             0
CardiacCount              0
MSKCount                  0
BeforeSlot                0
AfterSlot                 0
IsLast                    0
IsFirst                   0
DayOfWeek                 0
Month                     0
DayOfYear                 0
InProgressSize            0
NumCompletedToday         0
NumCompletedInLastW1      0
NumCompletedInLastW2      0
NumCompletedInLastW3      0
NumCustomersInLastW1      0
NumCustomersInLastW2      0
NumCustomersInLastW3      0
OutpatientWaitingCount    0
MalesWaitingCount         0
NumAddOnsToday            0
NumAddOnsLastW2           0
NumScheduledNextSlot      0
dtype: int64

In [25]:
df['x_ScheduledHour'] = df['x_ScheduledDTTM'].map(lambda date: date.hour)
df['x_ScheduledMinute'] = df['x_ScheduledDTTM'].map(lambda date: date.minute)

In [26]:
df.head()

,Wait,x_ScheduledDTTM,DelayCount,DelayCountLastHour,AheadCount,ThoracicCount,PediatricCount,NeuroCount,AbdominalCount,VascularCount,...,NumCustomersInLastW1,NumCustomersInLastW2,NumCustomersInLastW3,OutpatientWaitingCount,MalesWaitingCount,NumAddOnsToday,NumAddOnsLastW2,NumScheduledNextSlot,x_ScheduledHour,x_ScheduledMinute
0,23,2025-08-02 18:45:00,15,2,35,0,0,7,0,0,...,2,3,7,5,2,1,0,0,18,45
1,13,2025-08-02 18:45:00,14,1,35,0,0,6,0,0,...,2,5,7,5,2,1,0,0,18,45
2,16,2025-08-02 18:15:00,13,1,34,0,0,5,0,0,...,2,5,6,5,1,1,0,2,18,15
3,35,2025-08-02 17:45:00,13,1,32,0,0,4,1,0,...,4,4,7,5,2,1,0,1,17,45
4,65,2025-08-02 16:45:00,13,2,28,0,0,4,1,0,...,3,4,8,4,2,1,0,1,16,45

In [27]:
df = df.drop('x_ScheduledDTTM', axis=1)

In [28]:
df.head()

,Wait,DelayCount,DelayCountLastHour,AheadCount,ThoracicCount,PediatricCount,NeuroCount,AbdominalCount,VascularCount,CardiacCount,...,NumCustomersInLastW1,NumCustomersInLastW2,NumCustomersInLastW3,OutpatientWaitingCount,MalesWaitingCount,NumAddOnsToday,NumAddOnsLastW2,NumScheduledNextSlot,x_ScheduledHour,x_ScheduledMinute
0,23,15,2,35,0,0,7,0,0,0,...,2,3,7,5,2,1,0,0,18,45
1,13,14,1,35,0,0,6,0,0,0,...,2,5,7,5,2,1,0,0,18,45
2,16,13,1,34,0,0,5,0,0,0,...,2,5,6,5,1,1,0,2,18,15
3,35,13,1,32,0,0,4,1,0,0,...,4,4,7,5,2,1,0,1,17,45
4,65,13,2,28,0,0,4,1,0,0,...,3,4,8,4,2,1,0,1,16,45

In [29]:
df.to_csv('WaitDataF2', index=False)

In [30]:
df=pd.read_excel('WaitData.Published.xlsx', 'F3')

In [31]:
df.head()

,Wait,x_ArrivalDTTM,x_ScheduledDTTM,x_BeginDTTM,SumHowEarlyWaiting,AvgHowEarlyWaiting,LineCount0Strict,SumWaits,LineCount0,LineCount1,...,NumAddOnsToday,NumAddOnsLastW2,NumScheduledNextSlot,NumScheduledNextW2,SumTimeToCompleteNextSlot,SumTimeToCompleteNextW2,WithContrastCountWaiting,WithAndWithoutContrastCountWaiting,WithContrastCountInProgress,WithAndWithoutContrastCountInProgress
0,0,2025-08-02 16:47:44,2025-08-02 17:45:00,2025-08-02 17:45:03,372,62,6,249,6,5,...,4,2,0,0,0,0,3,1,1,0
1,-3,2025-08-02 16:38:46,2025-08-02 17:15:00,2025-08-02 17:12:14,335,67,3,195,5,4,...,4,1,2,0,32,0,2,1,2,0
2,-25,2025-08-02 16:29:25,2025-08-02 17:30:00,2025-08-02 17:05:15,274,68,4,150,4,5,...,4,1,1,1,13,16,1,1,3,0
3,36,2025-08-02 16:16:24,2025-08-02 16:45:00,2025-08-02 17:21:55,369,73,2,179,5,6,...,3,1,2,1,45,16,3,1,1,0
4,-21,2025-08-02 16:04:36,2025-08-02 17:15:00,2025-08-02 16:54:49,438,73,5,192,6,5,...,3,0,2,1,32,15,4,0,0,1

In [32]:
df = df.drop(drop_column, axis=1)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23583 entries, 0 to 23582
Data columns (total 32 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Wait                    23583 non-null  int64
 1   x_ScheduledDTTM         23583 non-null  datetime64[ns]
 2   DelayCount              23583 non-null  int64
 3   DelayCountLastHour      23583 non-null  int64
 4   AheadCount              23583 non-null  int64
 5   ThoracicCount           23583 non-null  int64
 6   PediatricCount          23583 non-null  int64
 7   NeuroCount              23583 non-null  int64
 8   AbdominalCount          23583 non-null  int64
 9   VascularCount           23583 non-null  int64
 10  CardiacCount            23583 non-null  int64
 11  MSKCount                23583 non-null  int64
 12  BeforeSlot              23583 non-null  int64
 13  AfterSlot               23583 non-null  int64
 14  IsLast                  23583 non-null  int64
 15  IsFirst                 23583 non-null  int64
 16  DayOfWeek               23583 non-null  int64
 17  Month                   23583 non-null  int64
 18  DayOfYear               23583 non-null  int64
 19  InProgressSize          23583 non-null  int64
 20  NumCompletedToday       23583 non-null  int64
 21  NumCompletedInLastW1    23583 non-null  int64
 22  NumCompletedInLastW2    23583 non-null  int64
 23  NumCompletedInLastW3    23583 non-null  int64
 24  NumCustomersInLastW1    23583 non-null  int64
 25  NumCustomersInLastW2    23583 non-null  int64
 26  NumCustomersInLastW3    23583 non-null  int64
 27  OutpatientWaitingCount  23583 non-null  int64
 28  MalesWaitingCount       23583 non-null  int64
 29  NumAddOnsToday          23583 non-null  int64
 30  NumAddOnsLastW2         23583 non-null  int64
 31  NumScheduledNextSlot    23583 non-null  int64
dtypes: datetime64[ns](1), int64(31)
memory usage: 5.8 MB

In [34]:
df.isnull().sum()

Wait                      0
x_ScheduledDTTM           0
DelayCount                0
DelayCountLastHour        0
AheadCount                0
ThoracicCount             0
PediatricCount            0
NeuroCount                0
AbdominalCount            0
VascularCount             0
CardiacCount              0
MSKCount                  0
BeforeSlot                0
AfterSlot                 0
IsLast                    0
IsFirst                   0
DayOfWeek                 0
Month                     0
DayOfYear                 0
InProgressSize            0
NumCompletedToday         0
NumCompletedInLastW1      0
NumCompletedInLastW2      0
NumCompletedInLastW3      0
NumCustomersInLastW1      0
NumCustomersInLastW2      0
NumCustomersInLastW3      0
OutpatientWaitingCount    0
MalesWaitingCount         0
NumAddOnsToday            0
NumAddOnsLastW2           0
NumScheduledNextSlot      0
dtype: int64

In [35]:
df['x_ScheduledHour'] = df['x_ScheduledDTTM'].map(lambda date: date.hour)
df['x_ScheduledMinute'] = df['x_ScheduledDTTM'].map(lambda date: date.minute)

In [36]:
df.head()

,Wait,x_ScheduledDTTM,DelayCount,DelayCountLastHour,AheadCount,ThoracicCount,PediatricCount,NeuroCount,AbdominalCount,VascularCount,...,NumCustomersInLastW1,NumCustomersInLastW2,NumCustomersInLastW3,OutpatientWaitingCount,MalesWaitingCount,NumAddOnsToday,NumAddOnsLastW2,NumScheduledNextSlot,x_ScheduledHour,x_ScheduledMinute
0,0,2025-08-02 17:45:00,15,2,42,4,0,0,1,1,...,3,8,12,7,3,4,2,0,17,45
1,-3,2025-08-02 17:15:00,15,3,38,4,0,0,1,1,...,3,7,11,6,2,4,1,2,17,15
2,-25,2025-08-02 17:30:00,15,4,40,3,0,0,2,1,...,3,6,11,5,1,4,1,1,17,30
3,36,2025-08-02 16:45:00,14,3,35,4,0,0,1,1,...,5,6,12,6,3,3,1,2,16,45
4,-21,2025-08-02 17:15:00,14,3,38,4,0,1,1,0,...,4,7,13,7,4,3,0,2,17,15

In [37]:
df = df.drop('x_ScheduledDTTM', axis=1)

In [40]:
df.describe()

,Wait,DelayCount,DelayCountLastHour,AheadCount,ThoracicCount,PediatricCount,NeuroCount,AbdominalCount,VascularCount,CardiacCount,...,NumCustomersInLastW1,NumCustomersInLastW2,NumCustomersInLastW3,OutpatientWaitingCount,MalesWaitingCount,NumAddOnsToday,NumAddOnsLastW2,NumScheduledNextSlot,x_ScheduledHour,x_ScheduledMinute
count,23583.000000,23583.000000,23583.000000,23583.000000,23583.000000,23583.000000,23583.000000,23583.000000,23583.000000,23583.000000,...,23583.000000,23583.000000,23583.000000,23583.000000,23583.000000,23583.000000,23583.000000,23583.000000,23583.000000,23583.000000
mean,8.399864,12.532333,3.074588,25.119111,4.312471,0.004834,0.465632,1.329432,0.377348,0.000721,...,3.744392,6.405292,11.265827,6.270110,3.132808,1.538820,0.599627,1.683119,12.772887,21.885256
std,48.299114,10.290544,2.201127,15.405156,2.305319,0.071171,0.698991,1.202781,0.647306,0.026840,...,1.697969,2.513185,4.199243,2.612099,1.784935,2.037477,0.886572,0.558773,2.571656,16.688249
min,-497.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,8.000000,0.000000
25%,-12.000000,3.000000,1.000000,12.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3.000000,5.000000,9.000000,4.000000,2.000000,0.000000,0.000000,1.000000,11.000000,0.000000
50%,12.000000,11.000000,3.000000,25.000000,4.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,4.000000,6.000000,12.000000,6.000000,3.000000,1.000000,0.000000,2.000000,12.000000,15.000000
75%,34.000000,21.000000,5.000000,38.000000,6.000000,0.000000,1.000000,2.000000,1.000000,0.000000,...,5.000000,8.000000,14.000000,8.000000,4.000000,2.000000,1.000000,2.000000,15.000000,30.000000
max,360.000000,50.000000,10.000000,68.000000,14.000000,2.000000,6.000000,9.000000,6.000000,1.000000,...,13.000000,19.000000,27.000000,18.000000,12.000000,13.000000,7.000000,6.000000,19.000000,50.000000

In [41]:
df.to_csv('WaitDataF3', index=False)